language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
  - node_modules
before_script:
  - node --version
script:
  - npm run chain:private
  - sleep 5
  - npm run test
# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: ./deploy.sh
#     on:
#       all_branches: true
#       tags: true
#       repo: o2oprotocol/o2oprotocol
#   - provider: npm
#     skip_cleanup: true
#     email: o2oprotocol101@gmail.com
#     api_key: $NPM_KEY
#     on:
#       all_branches: true
#       tags: true
#       repo: o2oprotocol/o2oprotocol
notifications:
  email: true
after_failure: cat /home/travis/build/o2oprotocol/o2oprotocol/npm-debug.log
