language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
  - node_modules
before_script:
  - node --version
script:
  - npm run chain:private
  - sleep 5
  - npm run migrate --network development
  - npm run test
deploy:
 - provider: script
   skip_cleanup: true
   script: npx truffle deploy --network development
   email: o2oprotocol101@gmail.com
   on:
     all_branches: true
     repo: o2oprotocol/o2oprotocol
env:
 - NODE_ENV=development
notifications:
  email: true
after_failure: cat /home/travis/build/o2oprotocol/o2oprotocol/npm-debug.log
